name: Generar APK Smart House

on:
  workflow_dispatch:

jobs:
  compilador:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar proyecto
        uses: actions/checkout@v4

      - name: Descomprimir proyecto
        run: |
          mkdir proyecto
          unzip -o SmartHouse_Corregido_HC05.zip -d proyecto

      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Instalar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.6'

      - name: Preparar proyecto Android
        run: |
          cd proyecto
          gradle wrapper --gradle-version 8.6

      - name: Compilar APK
        run: |
          cd proyecto
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: SmartHouse-APK
          path: proyecto/app/build/outputs/apk/debug/app-debug.apk
